asottile/add-trailing-comma

- add_trailing_comma.py
- tests/add_trailing_comma_test.py
> Properly detect parens when the function is parenthesized

- add_trailing_comma.py
- tests/add_trailing_comma_test.py
Resolves #7
I needed this refactor for my last feature anyway (since I need a second pass for that) so this is a nice win too.
> Also unhug stararg calls / functions

- README.md
- add_trailing_comma.py
- tests/add_trailing_comma_test.py
> Adjust trailing brace indentation to match opening brace

- add_trailing_comma.py
- setup.py
- tests/add_trailing_comma_test.py
> Better handle escaped newlines

- add_trailing_comma.py
- tests/add_trailing_comma_test.py
processing things top-down (instead of bottom-up) and handling all `(` makes things way better!
> Handle parenthesized things and more proper reindenting

- add_trailing_comma.py
Basically a partial reverse of #8 due to changes in #13
> Simplify functions now that we are handling unhug of (

- add_trailing_comma.py
- tests/add_trailing_comma_test.py
> Don't introduce trailing whitespace on blank lines when unhugging

- add_trailing_comma.py
- tests/add_trailing_comma_test.py
> Resolve commas in one stage for multi-line string nodes

- add_trailing_comma.py
- tests/add_trailing_comma_test.py
> Handle multiple functions in the same starting position

- add_trailing_comma.py
- tests/add_trailing_comma_test.py
> Special case handling tuples

- add_trailing_comma.py
- tests/add_trailing_comma_test.py
> Fix parsing of zero-length tokens

- add_trailing_comma.py
- tests/add_trailing_comma_test.py
> Fix extra comma in tuples which contain a fix in their first element

- README.md
- add_trailing_comma.py
- tests/add_trailing_comma_test.py
> Add trailing commas for from imports

- .travis.yml
- add_trailing_comma.py
> python 3.8 fixes

- add_trailing_comma.py
- tests/add_trailing_comma_test.py
> Reflow hugging more aggressively

- add_trailing_comma.py
> Ignore warnings

- add_trailing_comma.py
- setup.cfg
- tests/add_trailing_comma_test.py
> Use tokenize-rt 3.x

- add_trailing_comma.py
- tests/add_trailing_comma_test.py
> Add --exit-zero-even-if-changed

- add_trailing_comma.py
- tests/add_trailing_comma_test.py
> [multi-slice] Recognize multi-slice tuples

- tests/add_trailing_comma_test.py
See also https://github.com/asottile/pyupgrade/pull/225
> Add failing test for py27 ast.parse(<unicode>)

- .pre-commit-config.yaml
- add_trailing_comma.py
- azure-pipelines.yml
- setup.cfg
- tests/add_trailing_comma_test.py
- tox.ini
[python 3 statement](https://github.com/asottile/scratch/wiki/python-3-statement)
> add-trailing-comma: python3.6+

- add_trailing_comma.py
- azure-pipelines.yml
- tests/add_trailing_comma_test.py
- tox.ini
> work around python3.9 parser bug

- add_trailing_comma/_data.py
- add_trailing_comma/_main.py
- add_trailing_comma/_plugins/calls.py
- add_trailing_comma/_plugins/classes.py
- add_trailing_comma/_plugins/functions.py
- add_trailing_comma/_plugins/imports.py
- add_trailing_comma/_plugins/literals.py
this structure works better for pyupgrade
> use version in the ast parsing instead of the tokenizing

- add_trailing_comma/_plugins/literals.py
- tests/features/literals_test.py
> fix tuple rewrite in py38+ where first arg is parenthesized

- add_trailing_comma/_ast_helpers.py
- add_trailing_comma/_plugins/literals.py
- add_trailing_comma/_plugins/match.py
- requirements-dev.txt
Committed via https://github.com/asottile/all-repos
> improve coverage pragmas with covdefaults 2.1

- add_trailing_comma/_plugins/match.py
- tests/features/match_test.py
> fix match sequence without braces

- add_trailing_comma/_plugins/match.py
- tests/features/match_test.py
> skip fixing MatchClass with no args

- README.md
- add_trailing_comma/_plugins/_with.py
- tests/features/with_test.py
> adding multi-with-statements support

- README.md
> remove obsolete sections
